config/routes.rb
Studentlisting::Application.routes.draw do
  get "home/index"

  resources :entries
  
  root 'home#index'

end

app/models/entry.rb
class Entry < ActiveRecord::Base
  #validates :email_address, presence: true
  include Gravtastic
  gravtastic
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController

   
  def index
    @entries = Entry.all
  end

  def new
    @entry = Entry.new
  end
  
  def create
    @entry = Entry.new(params[:entry].permit(:first_name, :last_name, :email_address, :gravatarimage_image_url))
    flash[:notice] = "Entry successfully made!!"
    if @entry.save
       redirect_to @entry
    else
      render 'new'
    end
  end
  
  def show
    @entry = Entry.find(params[:id])
  end
  
  def edit
    @entry = Entry.find(params[:id])
    
  end
  
  def update
    @entry = Entry.find(params[:id])
    flash[:notice] = "Entry successfully edited!!"
    if @entry.update(params[:entry].permit(:first_name, :last_name, :email_address, :gravatarimage_image_url))
      redirect_to @entry
    else 
      render 'edit'
    end
  end
  
  def destroy
    @entry = Entry.find(params[:id])
    @entry.destroy
    flash[:notice] = "Entry successfully deleted!!"
    redirect_to entries_path
  end
    
  private
  def entry_params
    params.require(:entry).permit(:first_name, :last_name, :email_address, :gravatarimage_image_url)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_url(entry)
    gravatar_id = Digest::MD5::hexdigest(entry.email_address).downcase
    "http://gravatar.com/avatar/#{gravatar_id}.png"
  end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/entries/edit.html.erb
<h1>Student Entry Edit</h1>
<% if flash[:notice] %>
<div class="notice"><%= flash[:notice] %></div>
<% end %>
<br>
<%= form_for :entry, url: entry_path(@entry), method: :patch do |f| %>
<% if @entry.errors.any? %>
<div id="error_explanation">
  <h3><%= pluralize(@entry.errors.count, "error") %> found. Please fix before attempting to resubmit.</h3>
  <ul>
    <% @entry.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>
  <p>
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </p>
 
  <p>
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </p>

  <p>
    <%= f.label :email_address %><br>
    <%= f.text_field :email_address %>
  </p>

 
  <p>
    <%= f.submit %>
  </p>
<% end %>
<%= link_to 'Back', entries_path %>

app/views/entries/index.html.erb
<h1>Bueller Student Directory</h1>
<% if flash[:notice] %>
<div class="notice"><%= flash[:notice] %></div>
<% end %>
<br>
<%= link_to 'New Student Entry', new_entry_path %>
<br>
<table>
  <tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>E-mail Address</th>
    <th>Gravatar Image</th>
  </tr>
  
  <% @entries.each do |e| %>
  <tr>
    <td><%= e.first_name %></td>
    <td><%= e.last_name %></td>
    <td><%= e.email_address %></td>
    <td><%= image_tag avatar_url(e) %></td>
    <td><%= link_to 'Show', entry_path(e) %></td>
    <td><%= link_to 'Edit', edit_entry_path(e) %></td>
    <td><%= link_to 'Delete', entry_path(e), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
  <% end %>
</table>

app/views/entries/new.html.erb
<h1>New student entry</h1>

<%= form_for :entry, url: entries_path do |f| %>
   <% if @entry.errors.any? %>
   <div id="error_explanation">
     <h3><%= pluralize(@entry.errors.count, "error") %> found. Please fix before attempting to resubmit.</h3>
     <ul>
       <% @entry.errors.full_messages.each do |msg| %>
       <li><%= msg %></li>
       <% end %>
     </ul>
   </div>
   <% end %>
  <p>
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </p>
 
  <p>
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </p>

  <p>
    <%= f.label :email_address %><br>
    <%= f.text_field :email_address %>
  </p>

 
  <p>
    <%= f.submit %>
  </p>
<% end %>
<%= link_to 'Back', entries_path %>

app/views/entries/show.html.erb
<% if flash[:notice] %>
<div class="notice"><%= flash[:notice] %></div>
<% end %>
<br>
<p>
  <strong>First Name:</strong>
  <%= @entry.first_name %>
</p>
<p>
  <strong>Last Name:</strong>
  <%= @entry.last_name %>
</p>
<p>
  <strong>E-mail Address:</strong>
  <%= @entry.email_address %>
</p>
<p>
  <strong>Gravatar Image:</strong>
  <%= image_tag avatar_url(@entry) %>
</p>
<%= link_to 'Back', entries_path %>

app/views/home/index.html.erb
<h1>Bueller Student Directory</h1>
<p>Enter the directory below.</p>
<%= link_to "Student Directory Contents", controller: "entries" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Studentlisting</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>